### ISSUE TITLE
1.3.0 doesn't work on self-hosted Windows runners again

### ISSUE THREAD

**Issue by nazar-pc** [taiki-e/cache-cargo-install-action#4]
Upgraded from 1.2.2 to 1.3.0 and got this:
> C:\actions-runner\_work\_temp\1a3e4750-cac3-441d-91ea-03cc4119aa4e.sh: line 12: syntax error: unexpected end of file

https://github.com/subspace/subspace/actions/runs/8103393435/job/22147908717

**Comment by taiki-e** [comment]
>  line 12: syntax error: unexpected end of file

line 12 is `fi`. "If the `if` is on a single line, the `;` is necessary before `fi`", so it is not necessary here, but if there is a bug in the environment, such as the line break code being changed, adding a `;` after the `sleep "${i}"` (line 11) may fix the problem.

https://github.com/taiki-e/cache-cargo-install-action/blob/e87bd8424a739d2bebaeeed78c096f9db62063d4/pre.sh#L11-L12

**Comment by taiki-e** [comment]
FYI, [here](https://github.com/taiki-e/cache-cargo-install-action/compare/v1.2.2...v1.3.0) is the diff between 1.2.2 to 1.3.0 (only action.yml and pre.sh are called in an action call), but I have no idea what affected the portability.

**Comment by taiki-e** [comment]
Assuming that my guess in https://github.com/taiki-e/cache-cargo-install-action/issues/4#issuecomment-1973667201 is correct, I have created a patch in `debug` branch: https://github.com/taiki-e/cache-cargo-install-action/commit/ffcd4c5971feb6f7674fc2d7a4305b373511ace0

(However, if the above guess is correct, I believe the right place to fix the problem is on the self-hosted runner side, not in this repository.)

**Comment by nazar-pc** [comment]
2.0.0 seems to work on our self-hosted runners and ultimately if it doesn't the diff on our runners is probably what needs to be resolved. Closing and thanks for support!
